export const revalidate = 86400; // 👈 Ensures ISR is enabled for the entire page

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import HeaderWrapper from "@/components/headerWrapper/headerWrapper";
import Footer from "@/components/footer/footer";

import "./globals.css";
// import { Head } from "next/document";

const roboto = Roboto({
  adjustFontFallback: false,
  display: "swap",
  fallback: ["Helvetica Neue", "Helvetica", "Arial", "sans-serif"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <HeaderWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
